version: '3.8'

services:
  backend:
    build: ./backend
    container_name: social_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/social_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - social_network

  database:
    image: mysql:8.0
    container_name: social_database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - social_network

volumes:
  db_data:

networks:
  social_network:
